#!/usr/bin/env bash

## Description: Set up project for headless Drupal
## Usage: setup-drupal
## Example: "ddev setup-drupal"

if [ -d "/${DDEV_APPROOT}/frontend" ]; then
  cd "/${DDEV_APPROOT}/frontend" || exit ;
fi

if [ -e ./codegen.ts ] || [ -d ./app/api ]; then
  echo "Drupal setup can only be run once."
  echo "If you need the starter files, copy them from the /starterkits directory."
  exit 0;
fi

node lib/drupal/merge-package-json.js
cp ./starterkits/drupal/codegen.ts ./
cat ./starterkits/drupal/.env.drupal >> .env.local.example
cat ./starterkits/drupal/.env.drupal >> .env.local
rm -rf ./app
cp -r ./starterkits/drupal/app ./
mkdir ./util/drupal
cp -r ./starterkits/drupal/util/* ./util/drupal
rm -rf ./types
cp -r ./starterkits/drupal/types ./

# Block until file changes are in the web container...
if [ ${DDEV_MUTAGEN_ENABLED} ]; then
  ddev mutagen sync || true
fi

ddev exec -s=frontend "npm install --package-lock-only" || ddev exec "npm install --package-lock-only"
ddev exec -s=frontend "npm ci" || ddev exec "npm ci"
ddev exec -s=frontend "pm2 restart all" || ddev exec "pm2 restart all"
